// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/microhq/place-srv/proto/google/google.proto

/*
Package google is a generated protocol buffer package.

It is generated from these files:
	github.com/microhq/place-srv/proto/google/google.proto

It has these top-level messages:
	Price
	Geometry
	OpeningHours
	Photo
	AltId
	NearBySearchRequest
	NearBySearchResponse
	TextSearchRequest
	TextSearchResponse
	RadarSearchRequest
	RadarSearchResponse
*/
package google

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/microhq/place-srv/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Price struct {
	MinPrice uint64 `protobuf:"varint,1,opt,name=min_price,json=minPrice" json:"min_price,omitempty"`
	MaxPrice uint64 `protobuf:"varint,2,opt,name=max_price,json=maxPrice" json:"max_price,omitempty"`
}

func (m *Price) Reset()                    { *m = Price{} }
func (m *Price) String() string            { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()               {}
func (*Price) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Price) GetMinPrice() uint64 {
	if m != nil {
		return m.MinPrice
	}
	return 0
}

func (m *Price) GetMaxPrice() uint64 {
	if m != nil {
		return m.MaxPrice
	}
	return 0
}

type Geometry struct {
	Location *common.Point `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
}

func (m *Geometry) Reset()                    { *m = Geometry{} }
func (m *Geometry) String() string            { return proto.CompactTextString(m) }
func (*Geometry) ProtoMessage()               {}
func (*Geometry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Geometry) GetLocation() *common.Point {
	if m != nil {
		return m.Location
	}
	return nil
}

type OpeningHours struct {
	OpenNow bool `protobuf:"varint,1,opt,name=open_now,json=openNow" json:"open_now,omitempty"`
}

func (m *OpeningHours) Reset()                    { *m = OpeningHours{} }
func (m *OpeningHours) String() string            { return proto.CompactTextString(m) }
func (*OpeningHours) ProtoMessage()               {}
func (*OpeningHours) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *OpeningHours) GetOpenNow() bool {
	if m != nil {
		return m.OpenNow
	}
	return false
}

type Photo struct {
	Height           uint64   `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	HtmlAttributions []string `protobuf:"bytes,2,rep,name=html_attributions,json=htmlAttributions" json:"html_attributions,omitempty"`
	PhotoReference   string   `protobuf:"bytes,3,opt,name=photo_reference,json=photoReference" json:"photo_reference,omitempty"`
	Width            uint64   `protobuf:"varint,4,opt,name=width" json:"width,omitempty"`
}

func (m *Photo) Reset()                    { *m = Photo{} }
func (m *Photo) String() string            { return proto.CompactTextString(m) }
func (*Photo) ProtoMessage()               {}
func (*Photo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Photo) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Photo) GetHtmlAttributions() []string {
	if m != nil {
		return m.HtmlAttributions
	}
	return nil
}

func (m *Photo) GetPhotoReference() string {
	if m != nil {
		return m.PhotoReference
	}
	return ""
}

func (m *Photo) GetWidth() uint64 {
	if m != nil {
		return m.Width
	}
	return 0
}

type AltId struct {
	PlaceId string `protobuf:"bytes,1,opt,name=place_id,json=placeId" json:"place_id,omitempty"`
	Scope   string `protobuf:"bytes,2,opt,name=scope" json:"scope,omitempty"`
}

func (m *AltId) Reset()                    { *m = AltId{} }
func (m *AltId) String() string            { return proto.CompactTextString(m) }
func (*AltId) ProtoMessage()               {}
func (*AltId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AltId) GetPlaceId() string {
	if m != nil {
		return m.PlaceId
	}
	return ""
}

func (m *AltId) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

type NearBySearchRequest struct {
	Location      *common.Point `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
	Radius        uint64        `protobuf:"varint,2,opt,name=radius" json:"radius,omitempty"`
	RankBy        string        `protobuf:"bytes,3,opt,name=rank_by,json=rankBy" json:"rank_by,omitempty"`
	Keyword       string        `protobuf:"bytes,4,opt,name=keyword" json:"keyword,omitempty"`
	Language      string        `protobuf:"bytes,5,opt,name=language" json:"language,omitempty"`
	Price         *Price        `protobuf:"bytes,6,opt,name=price" json:"price,omitempty"`
	Name          string        `protobuf:"bytes,7,opt,name=name" json:"name,omitempty"`
	OpenNow       bool          `protobuf:"varint,8,opt,name=open_now,json=openNow" json:"open_now,omitempty"`
	Types         []string      `protobuf:"bytes,9,rep,name=types" json:"types,omitempty"`
	PageToken     string        `protobuf:"bytes,10,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
	ZagatSelected bool          `protobuf:"varint,11,opt,name=zagat_selected,json=zagatSelected" json:"zagat_selected,omitempty"`
}

func (m *NearBySearchRequest) Reset()                    { *m = NearBySearchRequest{} }
func (m *NearBySearchRequest) String() string            { return proto.CompactTextString(m) }
func (*NearBySearchRequest) ProtoMessage()               {}
func (*NearBySearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *NearBySearchRequest) GetLocation() *common.Point {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *NearBySearchRequest) GetRadius() uint64 {
	if m != nil {
		return m.Radius
	}
	return 0
}

func (m *NearBySearchRequest) GetRankBy() string {
	if m != nil {
		return m.RankBy
	}
	return ""
}

func (m *NearBySearchRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *NearBySearchRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *NearBySearchRequest) GetPrice() *Price {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *NearBySearchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NearBySearchRequest) GetOpenNow() bool {
	if m != nil {
		return m.OpenNow
	}
	return false
}

func (m *NearBySearchRequest) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *NearBySearchRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *NearBySearchRequest) GetZagatSelected() bool {
	if m != nil {
		return m.ZagatSelected
	}
	return false
}

type NearBySearchResponse struct {
	HtmlAttributions []string                                   `protobuf:"bytes,1,rep,name=html_attributions,json=htmlAttributions" json:"html_attributions,omitempty"`
	Results          []*NearBySearchResponse_NearBySearchResult `protobuf:"bytes,2,rep,name=results" json:"results,omitempty"`
	Status           string                                     `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *NearBySearchResponse) Reset()                    { *m = NearBySearchResponse{} }
func (m *NearBySearchResponse) String() string            { return proto.CompactTextString(m) }
func (*NearBySearchResponse) ProtoMessage()               {}
func (*NearBySearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *NearBySearchResponse) GetHtmlAttributions() []string {
	if m != nil {
		return m.HtmlAttributions
	}
	return nil
}

func (m *NearBySearchResponse) GetResults() []*NearBySearchResponse_NearBySearchResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *NearBySearchResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type NearBySearchResponse_NearBySearchResult struct {
	Geometry     *Geometry     `protobuf:"bytes,1,opt,name=geometry" json:"geometry,omitempty"`
	Icon         string        `protobuf:"bytes,2,opt,name=icon" json:"icon,omitempty"`
	Id           string        `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Name         string        `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	OpeningHours *OpeningHours `protobuf:"bytes,5,opt,name=opening_hours,json=openingHours" json:"opening_hours,omitempty"`
	Photos       []*Photo      `protobuf:"bytes,6,rep,name=photos" json:"photos,omitempty"`
	PlaceId      string        `protobuf:"bytes,7,opt,name=place_id,json=placeId" json:"place_id,omitempty"`
	AltIds       []*AltId      `protobuf:"bytes,8,rep,name=alt_ids,json=altIds" json:"alt_ids,omitempty"`
	Reference    string        `protobuf:"bytes,9,opt,name=reference" json:"reference,omitempty"`
	Types        []string      `protobuf:"bytes,10,rep,name=types" json:"types,omitempty"`
	Vicinity     string        `protobuf:"bytes,11,opt,name=vicinity" json:"vicinity,omitempty"`
}

func (m *NearBySearchResponse_NearBySearchResult) Reset() {
	*m = NearBySearchResponse_NearBySearchResult{}
}
func (m *NearBySearchResponse_NearBySearchResult) String() string { return proto.CompactTextString(m) }
func (*NearBySearchResponse_NearBySearchResult) ProtoMessage()    {}
func (*NearBySearchResponse_NearBySearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0}
}

func (m *NearBySearchResponse_NearBySearchResult) GetGeometry() *Geometry {
	if m != nil {
		return m.Geometry
	}
	return nil
}

func (m *NearBySearchResponse_NearBySearchResult) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *NearBySearchResponse_NearBySearchResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NearBySearchResponse_NearBySearchResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NearBySearchResponse_NearBySearchResult) GetOpeningHours() *OpeningHours {
	if m != nil {
		return m.OpeningHours
	}
	return nil
}

func (m *NearBySearchResponse_NearBySearchResult) GetPhotos() []*Photo {
	if m != nil {
		return m.Photos
	}
	return nil
}

func (m *NearBySearchResponse_NearBySearchResult) GetPlaceId() string {
	if m != nil {
		return m.PlaceId
	}
	return ""
}

func (m *NearBySearchResponse_NearBySearchResult) GetAltIds() []*AltId {
	if m != nil {
		return m.AltIds
	}
	return nil
}

func (m *NearBySearchResponse_NearBySearchResult) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *NearBySearchResponse_NearBySearchResult) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *NearBySearchResponse_NearBySearchResult) GetVicinity() string {
	if m != nil {
		return m.Vicinity
	}
	return ""
}

type TextSearchRequest struct {
	Location      *common.Point `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
	Radius        uint64        `protobuf:"varint,2,opt,name=radius" json:"radius,omitempty"`
	Query         string        `protobuf:"bytes,3,opt,name=query" json:"query,omitempty"`
	Language      string        `protobuf:"bytes,4,opt,name=language" json:"language,omitempty"`
	Price         *Price        `protobuf:"bytes,5,opt,name=price" json:"price,omitempty"`
	Name          string        `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
	OpenNow       bool          `protobuf:"varint,7,opt,name=open_now,json=openNow" json:"open_now,omitempty"`
	Types         []string      `protobuf:"bytes,8,rep,name=types" json:"types,omitempty"`
	ZagatSelected bool          `protobuf:"varint,9,opt,name=zagat_selected,json=zagatSelected" json:"zagat_selected,omitempty"`
	PageToken     string        `protobuf:"bytes,10,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
}

func (m *TextSearchRequest) Reset()                    { *m = TextSearchRequest{} }
func (m *TextSearchRequest) String() string            { return proto.CompactTextString(m) }
func (*TextSearchRequest) ProtoMessage()               {}
func (*TextSearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *TextSearchRequest) GetLocation() *common.Point {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *TextSearchRequest) GetRadius() uint64 {
	if m != nil {
		return m.Radius
	}
	return 0
}

func (m *TextSearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *TextSearchRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *TextSearchRequest) GetPrice() *Price {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *TextSearchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TextSearchRequest) GetOpenNow() bool {
	if m != nil {
		return m.OpenNow
	}
	return false
}

func (m *TextSearchRequest) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *TextSearchRequest) GetZagatSelected() bool {
	if m != nil {
		return m.ZagatSelected
	}
	return false
}

func (m *TextSearchRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type TextSearchResponse struct {
	HtmlAttributions []string                               `protobuf:"bytes,1,rep,name=html_attributions,json=htmlAttributions" json:"html_attributions,omitempty"`
	Results          []*TextSearchResponse_TextSearchResult `protobuf:"bytes,2,rep,name=results" json:"results,omitempty"`
	Status           string                                 `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *TextSearchResponse) Reset()                    { *m = TextSearchResponse{} }
func (m *TextSearchResponse) String() string            { return proto.CompactTextString(m) }
func (*TextSearchResponse) ProtoMessage()               {}
func (*TextSearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *TextSearchResponse) GetHtmlAttributions() []string {
	if m != nil {
		return m.HtmlAttributions
	}
	return nil
}

func (m *TextSearchResponse) GetResults() []*TextSearchResponse_TextSearchResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *TextSearchResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type TextSearchResponse_TextSearchResult struct {
	Geometry         *Geometry     `protobuf:"bytes,1,opt,name=geometry" json:"geometry,omitempty"`
	Icon             string        `protobuf:"bytes,2,opt,name=icon" json:"icon,omitempty"`
	Id               string        `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Name             string        `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	OpeningHours     *OpeningHours `protobuf:"bytes,5,opt,name=opening_hours,json=openingHours" json:"opening_hours,omitempty"`
	Photos           []*Photo      `protobuf:"bytes,6,rep,name=photos" json:"photos,omitempty"`
	PlaceId          string        `protobuf:"bytes,7,opt,name=place_id,json=placeId" json:"place_id,omitempty"`
	AltIds           []*AltId      `protobuf:"bytes,8,rep,name=alt_ids,json=altIds" json:"alt_ids,omitempty"`
	Reference        string        `protobuf:"bytes,9,opt,name=reference" json:"reference,omitempty"`
	Types            []string      `protobuf:"bytes,10,rep,name=types" json:"types,omitempty"`
	FormattedAddress string        `protobuf:"bytes,11,opt,name=formatted_address,json=formattedAddress" json:"formatted_address,omitempty"`
}

func (m *TextSearchResponse_TextSearchResult) Reset()         { *m = TextSearchResponse_TextSearchResult{} }
func (m *TextSearchResponse_TextSearchResult) String() string { return proto.CompactTextString(m) }
func (*TextSearchResponse_TextSearchResult) ProtoMessage()    {}
func (*TextSearchResponse_TextSearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 0}
}

func (m *TextSearchResponse_TextSearchResult) GetGeometry() *Geometry {
	if m != nil {
		return m.Geometry
	}
	return nil
}

func (m *TextSearchResponse_TextSearchResult) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *TextSearchResponse_TextSearchResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TextSearchResponse_TextSearchResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TextSearchResponse_TextSearchResult) GetOpeningHours() *OpeningHours {
	if m != nil {
		return m.OpeningHours
	}
	return nil
}

func (m *TextSearchResponse_TextSearchResult) GetPhotos() []*Photo {
	if m != nil {
		return m.Photos
	}
	return nil
}

func (m *TextSearchResponse_TextSearchResult) GetPlaceId() string {
	if m != nil {
		return m.PlaceId
	}
	return ""
}

func (m *TextSearchResponse_TextSearchResult) GetAltIds() []*AltId {
	if m != nil {
		return m.AltIds
	}
	return nil
}

func (m *TextSearchResponse_TextSearchResult) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *TextSearchResponse_TextSearchResult) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *TextSearchResponse_TextSearchResult) GetFormattedAddress() string {
	if m != nil {
		return m.FormattedAddress
	}
	return ""
}

type RadarSearchRequest struct {
	Location      *common.Point `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
	Radius        uint64        `protobuf:"varint,2,opt,name=radius" json:"radius,omitempty"`
	Keyword       string        `protobuf:"bytes,3,opt,name=keyword" json:"keyword,omitempty"`
	Price         *Price        `protobuf:"bytes,4,opt,name=price" json:"price,omitempty"`
	Name          string        `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	OpenNow       bool          `protobuf:"varint,6,opt,name=open_now,json=openNow" json:"open_now,omitempty"`
	Types         []string      `protobuf:"bytes,7,rep,name=types" json:"types,omitempty"`
	ZagatSelected bool          `protobuf:"varint,8,opt,name=zagat_selected,json=zagatSelected" json:"zagat_selected,omitempty"`
}

func (m *RadarSearchRequest) Reset()                    { *m = RadarSearchRequest{} }
func (m *RadarSearchRequest) String() string            { return proto.CompactTextString(m) }
func (*RadarSearchRequest) ProtoMessage()               {}
func (*RadarSearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *RadarSearchRequest) GetLocation() *common.Point {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *RadarSearchRequest) GetRadius() uint64 {
	if m != nil {
		return m.Radius
	}
	return 0
}

func (m *RadarSearchRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *RadarSearchRequest) GetPrice() *Price {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *RadarSearchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RadarSearchRequest) GetOpenNow() bool {
	if m != nil {
		return m.OpenNow
	}
	return false
}

func (m *RadarSearchRequest) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *RadarSearchRequest) GetZagatSelected() bool {
	if m != nil {
		return m.ZagatSelected
	}
	return false
}

type RadarSearchResponse struct {
	HtmlAttributions []string                                 `protobuf:"bytes,1,rep,name=html_attributions,json=htmlAttributions" json:"html_attributions,omitempty"`
	Results          []*RadarSearchResponse_RadarSearchResult `protobuf:"bytes,2,rep,name=results" json:"results,omitempty"`
	Status           string                                   `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *RadarSearchResponse) Reset()                    { *m = RadarSearchResponse{} }
func (m *RadarSearchResponse) String() string            { return proto.CompactTextString(m) }
func (*RadarSearchResponse) ProtoMessage()               {}
func (*RadarSearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *RadarSearchResponse) GetHtmlAttributions() []string {
	if m != nil {
		return m.HtmlAttributions
	}
	return nil
}

func (m *RadarSearchResponse) GetResults() []*RadarSearchResponse_RadarSearchResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *RadarSearchResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type RadarSearchResponse_RadarSearchResult struct {
	Geometry *Geometry `protobuf:"bytes,1,opt,name=geometry" json:"geometry,omitempty"`
	PlaceId  string    `protobuf:"bytes,2,opt,name=place_id,json=placeId" json:"place_id,omitempty"`
}

func (m *RadarSearchResponse_RadarSearchResult) Reset()         { *m = RadarSearchResponse_RadarSearchResult{} }
func (m *RadarSearchResponse_RadarSearchResult) String() string { return proto.CompactTextString(m) }
func (*RadarSearchResponse_RadarSearchResult) ProtoMessage()    {}
func (*RadarSearchResponse_RadarSearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{10, 0}
}

func (m *RadarSearchResponse_RadarSearchResult) GetGeometry() *Geometry {
	if m != nil {
		return m.Geometry
	}
	return nil
}

func (m *RadarSearchResponse_RadarSearchResult) GetPlaceId() string {
	if m != nil {
		return m.PlaceId
	}
	return ""
}

func init() {
	proto.RegisterType((*Price)(nil), "Price")
	proto.RegisterType((*Geometry)(nil), "Geometry")
	proto.RegisterType((*OpeningHours)(nil), "OpeningHours")
	proto.RegisterType((*Photo)(nil), "Photo")
	proto.RegisterType((*AltId)(nil), "AltId")
	proto.RegisterType((*NearBySearchRequest)(nil), "NearBySearchRequest")
	proto.RegisterType((*NearBySearchResponse)(nil), "NearBySearchResponse")
	proto.RegisterType((*NearBySearchResponse_NearBySearchResult)(nil), "NearBySearchResponse.NearBySearchResult")
	proto.RegisterType((*TextSearchRequest)(nil), "TextSearchRequest")
	proto.RegisterType((*TextSearchResponse)(nil), "TextSearchResponse")
	proto.RegisterType((*TextSearchResponse_TextSearchResult)(nil), "TextSearchResponse.TextSearchResult")
	proto.RegisterType((*RadarSearchRequest)(nil), "RadarSearchRequest")
	proto.RegisterType((*RadarSearchResponse)(nil), "RadarSearchResponse")
	proto.RegisterType((*RadarSearchResponse_RadarSearchResult)(nil), "RadarSearchResponse.RadarSearchResult")
}

func init() {
	proto.RegisterFile("github.com/microhq/place-srv/proto/google/google.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 915 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x96, 0xdf, 0x6e, 0xe3, 0x44,
	0x14, 0xc6, 0x9b, 0x34, 0xf1, 0x9f, 0x93, 0xb6, 0xb4, 0xd3, 0x00, 0x26, 0x2c, 0x50, 0x59, 0x2c,
	0x14, 0xad, 0x70, 0xa4, 0x20, 0x01, 0x42, 0x02, 0xd1, 0xde, 0x2c, 0x7b, 0xb3, 0x54, 0xb3, 0xcb,
	0xb5, 0x35, 0xb5, 0x67, 0xed, 0x51, 0x6d, 0x8f, 0x3b, 0x33, 0xde, 0x36, 0xbc, 0x02, 0x6f, 0xc2,
	0x33, 0xf0, 0x02, 0x5c, 0xf3, 0x06, 0xbc, 0x02, 0x70, 0x8b, 0x90, 0xc7, 0x4e, 0x6a, 0x27, 0x4e,
	0x37, 0x5a, 0xed, 0x25, 0x57, 0xc9, 0xf9, 0x8e, 0xce, 0x78, 0xe6, 0x9c, 0xef, 0xe7, 0x31, 0x7c,
	0x19, 0x31, 0x15, 0x17, 0x97, 0x5e, 0xc0, 0xd3, 0x69, 0xca, 0x02, 0xc1, 0xe3, 0xeb, 0x69, 0x9e,
	0x90, 0x80, 0x7e, 0x2e, 0xc5, 0xcb, 0x69, 0x2e, 0xb8, 0xe2, 0xd3, 0x88, 0xf3, 0x28, 0xa1, 0xf5,
	0x8f, 0xa7, 0xb5, 0xc9, 0x74, 0x8b, 0xba, 0x80, 0xa7, 0x29, 0xcf, 0xaa, 0x02, 0xf7, 0x0c, 0x86,
	0x17, 0x82, 0x05, 0x14, 0xbd, 0x0f, 0x76, 0xca, 0x32, 0x3f, 0x2f, 0x03, 0xa7, 0x77, 0xd2, 0x3b,
	0x1d, 0x60, 0x2b, 0x65, 0xd9, 0x5d, 0x92, 0xdc, 0xd6, 0xc9, 0x7e, 0x9d, 0x24, 0xb7, 0x3a, 0xe9,
	0x7a, 0x60, 0x3d, 0xa6, 0x3c, 0xa5, 0x4a, 0xcc, 0x91, 0x0b, 0x56, 0xc2, 0x03, 0xa2, 0x18, 0xcf,
	0xf4, 0x22, 0xa3, 0x99, 0xe1, 0x5d, 0x70, 0x96, 0x29, 0xbc, 0xd4, 0xdd, 0xcf, 0x60, 0xef, 0xc7,
	0x9c, 0x66, 0x2c, 0x8b, 0x7e, 0xe0, 0x85, 0x90, 0xe8, 0x3d, 0xb0, 0x78, 0x4e, 0x33, 0x3f, 0xe3,
	0x37, 0xba, 0xc6, 0xc2, 0x66, 0x19, 0x3f, 0xe5, 0x37, 0xee, 0x2f, 0x3d, 0x18, 0x5e, 0xc4, 0x5c,
	0x71, 0xf4, 0x0e, 0x18, 0x31, 0x65, 0x51, 0xac, 0xea, 0xbd, 0xd5, 0x11, 0x7a, 0x04, 0x47, 0xb1,
	0x4a, 0x13, 0x9f, 0x28, 0x25, 0xd8, 0x65, 0x51, 0x3e, 0x40, 0x3a, 0xfd, 0x93, 0xdd, 0x53, 0x1b,
	0x1f, 0x96, 0x89, 0xb3, 0x86, 0x8e, 0x3e, 0x85, 0xb7, 0xf2, 0x72, 0x35, 0x5f, 0xd0, 0x17, 0x54,
	0xd0, 0x2c, 0xa0, 0xce, 0xee, 0x49, 0xef, 0xd4, 0xc6, 0x07, 0x5a, 0xc6, 0x0b, 0x15, 0x8d, 0x61,
	0x78, 0xc3, 0x42, 0x15, 0x3b, 0x03, 0xfd, 0xb0, 0x2a, 0x70, 0xbf, 0x86, 0xe1, 0x59, 0xa2, 0x9e,
	0x84, 0xe5, 0x8e, 0x75, 0x53, 0x7d, 0x16, 0xea, 0xed, 0xd8, 0xd8, 0xd4, 0xf1, 0x93, 0xb0, 0xac,
	0x94, 0x01, 0xcf, 0xab, 0x2e, 0xd9, 0xb8, 0x0a, 0xdc, 0xdf, 0xfb, 0x70, 0xfc, 0x94, 0x12, 0x71,
	0x3e, 0x7f, 0x46, 0x89, 0x08, 0x62, 0x4c, 0xaf, 0x0b, 0x2a, 0xd5, 0x36, 0xed, 0x2a, 0x4f, 0x2e,
	0x48, 0xc8, 0x0a, 0x59, 0x37, 0xbe, 0x8e, 0xd0, 0xbb, 0x60, 0x0a, 0x92, 0x5d, 0xf9, 0x97, 0xf3,
	0xfa, 0x10, 0x46, 0x19, 0x9e, 0xcf, 0x91, 0x03, 0xe6, 0x15, 0x9d, 0xdf, 0x70, 0x11, 0xea, 0xed,
	0xdb, 0x78, 0x11, 0xa2, 0x09, 0x58, 0x09, 0xc9, 0xa2, 0x82, 0x44, 0xd4, 0x19, 0xea, 0xd4, 0x32,
	0x46, 0x0f, 0x60, 0x58, 0x8d, 0xd7, 0x58, 0xec, 0xa3, 0x8c, 0x70, 0x25, 0x22, 0x04, 0x83, 0x8c,
	0xa4, 0xd4, 0x31, 0x75, 0x95, 0xfe, 0xdf, 0x9a, 0x9b, 0xd5, 0x9a, 0x5b, 0xd9, 0x05, 0x35, 0xcf,
	0xa9, 0x74, 0x6c, 0x3d, 0x89, 0x2a, 0x40, 0x1f, 0x00, 0xe4, 0x24, 0xa2, 0xbe, 0xe2, 0x57, 0x34,
	0x73, 0x40, 0x2f, 0x65, 0x97, 0xca, 0xf3, 0x52, 0x40, 0x0f, 0xe1, 0xe0, 0x67, 0x12, 0x11, 0xe5,
	0x4b, 0x9a, 0xd0, 0x40, 0xd1, 0xd0, 0x19, 0xe9, 0x55, 0xf7, 0xb5, 0xfa, 0xac, 0x16, 0xdd, 0x7f,
	0x76, 0x61, 0xdc, 0xee, 0xa5, 0xcc, 0x79, 0x26, 0x69, 0xb7, 0x15, 0x7a, 0x1b, 0xac, 0x70, 0x0e,
	0xa6, 0xa0, 0xb2, 0x48, 0x54, 0xe5, 0x96, 0xd1, 0xec, 0xd4, 0xeb, 0x5a, 0x74, 0x55, 0x2c, 0x12,
	0x85, 0x17, 0x85, 0xe5, 0x64, 0xa4, 0x22, 0xaa, 0x90, 0x8b, 0x01, 0x54, 0xd1, 0xe4, 0x8f, 0x3e,
	0xa0, 0xf5, 0x3a, 0xf4, 0x10, 0xac, 0xa8, 0xe6, 0xa4, 0x1e, 0xb6, 0xed, 0x2d, 0xc0, 0xc1, 0xcb,
	0x54, 0xd9, 0x6a, 0x16, 0xf0, 0xac, 0x36, 0x90, 0xfe, 0x8f, 0x0e, 0xa0, 0xcf, 0xc2, 0xfa, 0x29,
	0x7d, 0x16, 0x2e, 0xc7, 0x31, 0x68, 0x8c, 0x63, 0x06, 0xfb, 0xbc, 0xc2, 0xca, 0x8f, 0x4b, 0xae,
	0xf4, 0x84, 0x47, 0xb3, 0x7d, 0xaf, 0x09, 0x1b, 0xde, 0xe3, 0x4d, 0xf4, 0x3e, 0x04, 0x43, 0x3b,
	0x5f, 0x3a, 0x86, 0x6e, 0x82, 0xe1, 0x69, 0xda, 0x70, 0xad, 0xb6, 0x8c, 0x6e, 0xb6, 0x8d, 0xfe,
	0x11, 0x98, 0x24, 0x51, 0x3e, 0x0b, 0xa5, 0x63, 0xd5, 0xb5, 0x1a, 0x0e, 0x6c, 0x90, 0xf2, 0x47,
	0xa2, 0x07, 0x60, 0xdf, 0x61, 0x66, 0x57, 0xc3, 0x16, 0x4d, 0xc2, 0x2a, 0x87, 0x40, 0xd3, 0x21,
	0x13, 0xb0, 0x5e, 0xb2, 0x80, 0x65, 0x4c, 0xcd, 0xf5, 0xf0, 0x6d, 0xbc, 0x8c, 0xdd, 0x5f, 0xfb,
	0x70, 0xf4, 0x9c, 0xde, 0xaa, 0x37, 0x47, 0xd0, 0x18, 0x86, 0xd7, 0x05, 0x15, 0x0b, 0x7e, 0xaa,
	0xa0, 0x05, 0xc9, 0x60, 0x13, 0x24, 0xc3, 0xfb, 0x20, 0x31, 0x36, 0x40, 0x62, 0x6e, 0x80, 0xc4,
	0x6a, 0xb6, 0x60, 0x9d, 0x02, 0xbb, 0x83, 0x82, 0x57, 0xb0, 0xe4, 0xfe, 0xbb, 0x0b, 0xa8, 0xd9,
	0xac, 0xd7, 0x41, 0xe4, 0xbb, 0x55, 0x44, 0x3e, 0xf6, 0xd6, 0x97, 0x6c, 0x4b, 0x5b, 0xe1, 0xf1,
	0x67, 0x1f, 0x0e, 0x57, 0xab, 0xfe, 0x87, 0xe3, 0xd5, 0x70, 0x3c, 0x82, 0xa3, 0x17, 0x5c, 0xa4,
	0x44, 0x29, 0x1a, 0xfa, 0x24, 0x0c, 0x05, 0x95, 0xb2, 0xa6, 0xe4, 0x70, 0x99, 0x38, 0xab, 0x74,
	0xf7, 0xef, 0x1e, 0x20, 0x4c, 0x42, 0x22, 0xde, 0x1c, 0x2e, 0x8d, 0x7b, 0x65, 0xb7, 0x7d, 0xaf,
	0x2c, 0xb1, 0x18, 0xdc, 0x87, 0xc5, 0x70, 0x03, 0x16, 0xc6, 0x06, 0x2c, 0xcc, 0xfb, 0xb1, 0xb0,
	0xba, 0x2e, 0x87, 0xbf, 0x7a, 0x70, 0xdc, 0x3a, 0xf6, 0xeb, 0x18, 0xff, 0xfb, 0x55, 0xe3, 0x7f,
	0xe2, 0x75, 0xac, 0xb9, 0xa2, 0x6d, 0x65, 0xfd, 0x9f, 0xe0, 0x68, 0xad, 0x6a, 0x5b, 0xeb, 0x37,
	0xed, 0xd6, 0x6f, 0xd9, 0x6d, 0xf6, 0x5b, 0x0f, 0x8c, 0xc7, 0xfa, 0x33, 0x10, 0x7d, 0x0b, 0x7b,
	0xcd, 0xab, 0x07, 0x8d, 0xbd, 0x8e, 0xef, 0x8e, 0xc9, 0xdb, 0x9d, 0x97, 0x9d, 0xbb, 0x83, 0xbe,
	0x02, 0xb8, 0x43, 0x13, 0x21, 0x6f, 0xed, 0x85, 0x3b, 0x39, 0xee, 0x78, 0x09, 0xb8, 0x3b, 0xe8,
	0x1b, 0x18, 0x35, 0x4e, 0x86, 0x8e, 0xbd, 0x75, 0xf3, 0x4d, 0xc6, 0x5d, 0x6d, 0x74, 0x77, 0x2e,
	0x0d, 0xfd, 0x29, 0xfa, 0xc5, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x8f, 0x79, 0x34, 0xf5,
	0x0a, 0x00, 0x00,
}
