// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/microhq/place-srv/proto/location/location.proto

/*
Package location is a generated protocol buffer package.

It is generated from these files:
	github.com/microhq/place-srv/proto/location/location.proto

It has these top-level messages:
	Place
	CreateRequest
	CreateResponse
	ReadRequest
	ReadResponse
	UpdateRequest
	UpdateResponse
	DeleteRequest
	DeleteResponse
	SearchRequest
	SearchResponse
*/
package location

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/microhq/place-srv/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Place struct {
	Id          string        `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name        string        `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Location    *common.Point `protobuf:"bytes,3,opt,name=location" json:"location,omitempty"`
	Iata        string        `protobuf:"bytes,4,opt,name=iata" json:"iata,omitempty"`
	Address     string        `protobuf:"bytes,5,opt,name=address" json:"address,omitempty"`
	Phone       string        `protobuf:"bytes,6,opt,name=phone" json:"phone,omitempty"`
	Description string        `protobuf:"bytes,7,opt,name=description" json:"description,omitempty"`
	Tags        []string      `protobuf:"bytes,8,rep,name=tags" json:"tags,omitempty"`
}

func (m *Place) Reset()                    { *m = Place{} }
func (m *Place) String() string            { return proto.CompactTextString(m) }
func (*Place) ProtoMessage()               {}
func (*Place) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Place) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Place) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Place) GetLocation() *common.Point {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Place) GetIata() string {
	if m != nil {
		return m.Iata
	}
	return ""
}

func (m *Place) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Place) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Place) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Place) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type CreateRequest struct {
	Place *Place `protobuf:"bytes,1,opt,name=place" json:"place,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRequest) GetPlace() *Place {
	if m != nil {
		return m.Place
	}
	return nil
}

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ReadRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadResponse struct {
	Place *Place `protobuf:"bytes,1,opt,name=place" json:"place,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadResponse) GetPlace() *Place {
	if m != nil {
		return m.Place
	}
	return nil
}

type UpdateRequest struct {
	Place *Place `protobuf:"bytes,1,opt,name=place" json:"place,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateRequest) GetPlace() *Place {
	if m != nil {
		return m.Place
	}
	return nil
}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type DeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type SearchRequest struct {
	Query  string `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	Limit  uint64 `protobuf:"varint,4,opt,name=limit" json:"limit,omitempty"`
	Offset uint64 `protobuf:"varint,5,opt,name=offset" json:"offset,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type SearchResponse struct {
	Places []*Place `protobuf:"bytes,1,rep,name=places" json:"places,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SearchResponse) GetPlaces() []*Place {
	if m != nil {
		return m.Places
	}
	return nil
}

func init() {
	proto.RegisterType((*Place)(nil), "Place")
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "DeleteResponse")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
}

func init() {
	proto.RegisterFile("github.com/microhq/place-srv/proto/location/location.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xdd, 0x6e, 0x9b, 0x30,
	0x14, 0x0e, 0x09, 0xd0, 0xec, 0xa4, 0x90, 0xca, 0xaa, 0x26, 0x0b, 0xed, 0x07, 0x59, 0x9a, 0x54,
	0x69, 0x8b, 0x99, 0xba, 0xbb, 0xdd, 0x6e, 0x97, 0xbb, 0xa8, 0xa8, 0xf6, 0x00, 0x2e, 0xb8, 0x8d,
	0xa5, 0x80, 0x09, 0x76, 0x26, 0xed, 0x11, 0xf7, 0x20, 0x7b, 0x8f, 0xc9, 0x36, 0xce, 0x80, 0x9b,
	0xad, 0x77, 0xe7, 0x7c, 0xfe, 0xbe, 0xf3, 0xf3, 0x1d, 0x80, 0xcf, 0x4f, 0x42, 0xef, 0x4f, 0x0f,
	0xb4, 0x92, 0x4d, 0xd1, 0x88, 0xaa, 0x97, 0xfb, 0x63, 0xd1, 0x1d, 0x58, 0xc5, 0x77, 0xaa, 0xff,
	0x51, 0x74, 0xbd, 0xd4, 0xb2, 0x38, 0xc8, 0x8a, 0x69, 0x21, 0xdb, 0x73, 0x40, 0x2d, 0x9e, 0x15,
	0xff, 0xa1, 0xad, 0x64, 0xd3, 0x78, 0x01, 0xf9, 0x15, 0x40, 0x74, 0x67, 0x08, 0x28, 0x85, 0xa5,
	0xa8, 0x71, 0x90, 0x07, 0x37, 0x2f, 0xca, 0xa5, 0xa8, 0x11, 0x82, 0xb0, 0x65, 0x0d, 0xc7, 0x4b,
	0x8b, 0xd8, 0x18, 0x11, 0x58, 0xfb, 0x86, 0x78, 0x95, 0x07, 0x37, 0x9b, 0xdb, 0x98, 0xde, 0x49,
	0xd1, 0xea, 0xf2, 0x8c, 0x1b, 0x9d, 0x60, 0x9a, 0xe1, 0xd0, 0xe9, 0x4c, 0x8c, 0x30, 0x5c, 0xb0,
	0xba, 0xee, 0xb9, 0x52, 0x38, 0xb2, 0xb0, 0x4f, 0xd1, 0x35, 0x44, 0xdd, 0x5e, 0xb6, 0x1c, 0xc7,
	0x16, 0x77, 0x09, 0xca, 0x61, 0x53, 0x73, 0x55, 0xf5, 0xa2, 0xb3, 0xad, 0x2e, 0xec, 0xdb, 0x18,
	0x32, 0x5d, 0x34, 0x7b, 0x52, 0x78, 0x9d, 0xaf, 0x4c, 0x17, 0x13, 0x93, 0x1d, 0x24, 0x5f, 0x7a,
	0xce, 0x34, 0x2f, 0xf9, 0xf1, 0xc4, 0x95, 0x46, 0xaf, 0x20, 0xb2, 0xcb, 0xdb, 0xad, 0xec, 0xac,
	0x26, 0x2b, 0x1d, 0x48, 0xae, 0x20, 0xf5, 0x74, 0xd5, 0xc9, 0x56, 0x71, 0xf2, 0x1a, 0x36, 0x25,
	0x67, 0xb5, 0x97, 0xcf, 0x1c, 0x21, 0x1f, 0xe0, 0xd2, 0x3d, 0x3b, 0xfa, 0x3f, 0xca, 0xef, 0x20,
	0xf9, 0xde, 0xd5, 0xcf, 0x99, 0xc6, 0xd3, 0x87, 0x69, 0xde, 0x42, 0xf2, 0x95, 0x1f, 0xf8, 0xdf,
	0x02, 0xf3, 0x79, 0xae, 0x20, 0xf5, 0x84, 0x41, 0x72, 0x0f, 0xc9, 0x3d, 0x67, 0x7d, 0xb5, 0xf7,
	0x92, 0x6b, 0x88, 0x8e, 0x27, 0xde, 0xff, 0x1c, 0x54, 0x2e, 0x31, 0xe8, 0x41, 0x34, 0x42, 0xdb,
	0x1b, 0x85, 0xa5, 0x4b, 0xd0, 0x4b, 0x88, 0xe5, 0xe3, 0xa3, 0xe2, 0xda, 0xde, 0x28, 0x2c, 0x87,
	0x8c, 0x7c, 0x84, 0xd4, 0x17, 0x1d, 0x16, 0x7f, 0x03, 0xb1, 0x1d, 0x5a, 0xe1, 0x20, 0x5f, 0x8d,
	0x56, 0x19, 0xd0, 0xdb, 0xdf, 0x01, 0xac, 0xbf, 0xf9, 0xef, 0xe1, 0x3d, 0xc4, 0xce, 0x66, 0x94,
	0xd2, 0xc9, 0x79, 0xb2, 0x2d, 0x9d, 0xf9, 0xbf, 0x40, 0xef, 0x20, 0x34, 0x16, 0xa3, 0x4b, 0x3a,
	0x3a, 0x44, 0x96, 0xd0, 0xb1, 0xef, 0x64, 0x61, 0x6a, 0x3a, 0xb3, 0x50, 0x4a, 0x27, 0x26, 0x67,
	0x5b, 0x3a, 0x73, 0xd1, 0x92, 0x9d, 0x4d, 0x28, 0xa5, 0x13, 0x43, 0xb3, 0x2d, 0x9d, 0xf9, 0x67,
	0xc9, 0x6e, 0x59, 0x94, 0xd2, 0x89, 0x95, 0xd9, 0x96, 0x4e, 0x5d, 0x20, 0x8b, 0x87, 0xd8, 0xfe,
	0x43, 0x9f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x32, 0x72, 0x07, 0x35, 0xb2, 0x03, 0x00, 0x00,
}
